"""adiciona comodidades e associacao hotel

Revision ID: cabf07da68d0
Revises: 1e56fab15d49
Create Date: 2026-09-25 03:28:23.888521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cabf07da68d0'
down_revision: Union[str, None] = '1e56fab15d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comodidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('hotel_comodidade',
    sa.Column('hotel_id', sa.Uuid(), nullable=False),
    sa.Column('comodidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comodidade_id'], ['comodidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotel_id', 'comodidade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_comodidade')
    op.drop_table('comodidades')
    # ### end Alembic commands ###
